### ISSUE TITLE
模版中选择的背景图片，在点击“撤销”按钮之后，位置出现偏差。

### ISSUE THREAD

**Issue by nimohe** [suguoyao/vue-card-diy#2]
### 问题描述
在用浏览器打开的时候，会出现该问题。
用Chrome移动设备模拟器没有问题，手机端浏览器打开也没有问题。
> Chrome：PC浏览模式  72.0.3626.81

### bug复现
详见gif。
![test-2](https://user-images.githubusercontent.com/4018265/52335753-1f1f6180-2a3e-11e9-8446-aeeea2c8dfe2.gif)

**Comment by suguoyao** [comment]
@nimohe 感谢指出！已修复！
