### ISSUE TITLE
您好还在用fabric吗？

### ISSUE THREAD

**Issue by liskysun** [suguoyao/vue-card-diy#3]
我也在使用，目前遇到了多次创建fabric后卡顿的问题，不知是不是缓存的问题，可以交流下吗？
WX：LiSkysunCHN

**Comment by suguoyao** [comment]
@liskysun 卡顿可能和fabric没关系，大概率是你代码问题

**Comment by cooper1x** [comment]
@suguoyao 手指缩放的时候，卡顿比较严重。

**Comment by mengfei2611** [comment]
大的图片会卡顿，我在使用的时候控制了图片的大小。在生产的时候才使用，高清图片打印。




------------------ 原始邮件 ------------------
发件人: "linkstar"<notifications@github.com>; 
发送时间: 2019年9月2日(星期一) 下午4:35
收件人: "suguoyao/vue-card-diy"<vue-card-diy@noreply.github.com>; 
抄送: "Subscribed"<subscribed@noreply.github.com>; 
主题: Re: [suguoyao/vue-card-diy] 您好还在用fabric吗？ (#3)




@suguoyao 手指缩放的时候，卡顿比较严重。

**Comment by suguoyao** [comment]
@cooper1x  @mengfei2611 @liskysun 这个我有空看一下哈，感谢反馈🙂

**Comment by cooper1x** [comment]
@suguoyao 我想请教一下，如何设置纯色背景呢？
还有个问题是，我插入背景图片，这个图虽然是铺满了，但只是图片的一部分铺满，请问怎么解决这个问题呢

**Comment by suguoyao** [comment]
@cooper1x 我刚创建了个fabric.js交流q群（208538748），为了方便可以进来交流🙂

**Comment by cooper1x** [comment]
@suguoyao 好的呢，这个问题我刚刚在上面朋友的帮助下解决了
